### ISSUE TITLE
Fix bibliography linking

### ISSUE THREAD

**Issue by koppor** [gi-ev/LNI#107]
I reiterate on executing `pdflatex` and `biber` on `lni-paper-example-de` in texlive. The hyperlinks inside the main text work, but the links to the bibliography don't.

![grafik](https://github.com/gi-ev/LNI/assets/1366654/6f66f532-99ad-4707-b219-c9b9a89f575d)

No clue, what it wrong there.

**Comment by sieversMartin** [comment]
Well, if you explicitly turn on hyperref support for biblatex you get:
```
Package biblatex Warning: Missing 'hyperref' package.
(biblatex)                Setting 'hyperref=false'.
```

So although the package is loaded, biblatex seems to ignore it. The reason is unknown, it may be connected with a series of `\AtEndPreamble` calls.

**Comment by koppor** [comment]
Thank you for the hint. I think, I fixed it at https://github.com/gi-ev/LNI/pull/116.

**Comment by sieversMartin** [comment]
I suggest, we use a modern solution adding an appropriate hook, which is possible since kernel 2020/10/01. I'll do this.
