### ISSUE TITLE
Output of @misc Bibliography information includes ", " before title

### ISSUE THREAD

**Issue by YannickErb** [gi-ev/LNI#123]
I have an issue with the display of @misc bibliography information.

I have an online source I use within my paper. However, when using the @misc bibliography entry a ", " gets displayed in front of the Paper title (see attached file).

This is the Bibliography entry I am using:

@misc{author.2023,
 author = {AuthorName1, AuthorSurname1 and AuthorName2, AuthorSurname2 and Authorname3, AuthorSurname3},
 year = {2023},
 title = {Title},
 url = {myURL},
 howpublished = {\url{myURL}},
 urldate = {11.09.2023},
 note = {Accessed: 2023-09-11}
}

<img width="346" alt="MISC_Problem" src="https://github.com/gi-ev/LNI/assets/144433796/63d54905-a953-45fe-b88c-230b1e88eae6">

Any tips on how to resolve this?

Thank you in advance!

**Comment by YannickErb** [comment]
Thanks for the quick response:

As far as I know (I am not very fond at LaTeX) I am using bst files (the ones in the template, unchanged) and BibTeX.

I create the bibliography in the following way:

...
%%% Angabe der .bib-Datei (ohne Endung) / State .bib file (for BibTeX usage)
\bibliography{TestBibTex} %\printbibliography if you use biblatex/Biber
\end{document}

**Comment by YannickErb** [comment]
Thanks for the help. Using the files from the repository resolved the issue.

I was using the Overleaf-Template as was suggested by the conference chairs for the sake of simplicity.
https://de.overleaf.com/latex/templates/template-for-lecture-notes-in-informatics-lni-manuscripts/jkgrrgypgzps 

However, it seems that this template may be outdated.
Is there a way to quickly update all outdated files from the Overleaf-Template?

**Comment by sieversMartin** [comment]
First of all, using biblatex is the standard way of using references nowadays. This is reflected in the latest version of the LNI class as well. As soon as we have a stable version, I'll (try to) update the template in the Overleaf gallery.

**Comment by YannickErb** [comment]
Thank you for the information!
As the issue could be resolved by using the "new" version of the files from the GitHub repository, it seems that this issue will not be a problem in coming versions of the template. I will close the issue then and want to once again, thank you!
