### ISSUE TITLE
Default: no headings

### ISSUE THREAD

**Issue by koppor** [gi-ev/LNI#129]
Word does not have any titles any more - see https://gi.de/service/publikationen/lni

> Die neue Vorlage enthält keine Kopfzeilen und keine Paginierung. Die werden vom Herausgeber generiert.

Current Word template:

![image](https://github.com/gi-ev/LNI/assets/1366654/f3bc4863-96f2-48ae-92f7-9558d1bdd9aa)

We typeset:

![image](https://github.com/gi-ev/LNI/assets/1366654/794eb2f4-e6fd-4586-80e7-1e4dfd7b0f06)

**Comment by sieversMartin** [comment]
Already fixed as part of #121.

**Comment by koppor** [comment]
@sieversMartin Thank you for the quick reaction! Did not see it in `main` or a PR. Was about to introduce `runningheads`, but stopped now 🎉 .

**Comment by sieversMartin** [comment]
The changes have not been pushed.
