### ISSUE TITLE
Add missing font package to `Texlivefile`

### ISSUE THREAD

**Issue by koppor** [gi-ev/LNI#165]
With pdflatex, we get following error

```
! pdfTeX error (font expansion): auto expansion is only possible with scalable 
fonts.
<argument> ...shipout:D \box_use:N \l_shipout_box 
                                                  \__shipout_drop_firstpage_...
l.58 H
      ier eine kleine Demonstration von \href{https://www.ctan.org/pkg/micro...
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on lni-paper-example-de.log.
```

I think, a package is missing at https://github.com/gi-ev/LNI/blob/main/Texlivefile - but which one?

**Comment by sieversMartin** [comment]
That is a problem caused by `microtype` in connection with the used font. What fonts are loaded in your concrete example?

**Comment by koppor** [comment]
Complete log at https://github.com/gi-ev/LNI/actions/runs/8278733787/job/22652021047. 

![image](https://github.com/gi-ev/LNI/assets/1366654/ac42101e-9106-4554-bccb-5310055061aa)


It is our `lni-paper-example-de.tex`:

```latex
% !TeX encoding = UTF-8
% !TeX spellcheck = de_DE

\documentclass[biblatex]{lni}
\addbibresource{lni-paper-example-de.bib}

%% Schöne Tabellen mittels \toprule, \midrule, \bottomrule
\usepackage{booktabs}

%% Zu Demonstrationszwecken
\usepackage[]{blindtext}

\begin{document}
```

If I read the CLS correctly, it are following fonts:

```
            \RequirePackage[defaultsups]{newtxtext}
            \RequirePackage{newtxmath}
            \RequirePackage[zerostyle=b,scaled=.9]{newtxtt}
```

Maybe, it is a packaging error of `newtxtt` again and I should craft a minimal example?

**Comment by sieversMartin** [comment]
Real strange. I get the same error on my local machine. So, there must be some kind of recently introduced problem with the font.

**Comment by sieversMartin** [comment]
Options `oldfonts` and `nofonts` work.

**Comment by sieversMartin** [comment]
There was an update of the font in TL just today.

**Comment by koppor** [comment]
Then let's wait until tomorrow until all changes propagate to all mirrors.

**Comment by sieversMartin** [comment]
Well, I already had this version ...

**Comment by sieversMartin** [comment]
Changes in version 1.059
Added some missing entries in newtxtt.map affecting option zerostyle=e and straight quotes. (Thanks, Andre David Tinoco Mendes and Oliver Kopp.)

Changes in version 1.058
1. Corrected some technical errors in the bold versions 
of the fonts. (Thanks to Edgaras Šakuras for catching this.)
2. Expanded the TS1 coverage to honor the zerostyle option.

**Comment by koppor** [comment]
Works after a clean install of Texlive packages. --> https://github.com/gi-ev/LNI/actions/runs/8280700847/job/22657858860

Sorry for the noise!
