### ISSUE TITLE
\affil: ! Undefined control sequence.

### ISSUE THREAD

**Issue by jd-s** [gi-ev/LNI#169]
When trying to compile the new template (lni-author-template.tex) with pdflatex, I receive the following error:
```
! Undefined control sequence.
l.26 \affil
           [1]{Universität\\Abteilung\\Straße\\Postleitzahl Ort\\Land}
? 
```
Any idea how to solve this? Of course, this error persists when working on the paper...

Thank you!

**Comment by sieversMartin** [comment]
Which version of `lni.cls` do you use? `\affil` is a new macro defined in v1.8

**Comment by weberi** [comment]
I was facing this issue as well. It turned out that Latex used an outdated version of the LNI style from TexLive instead of the current version which I had downloaded manually. v1.8 works well for me.

**Comment by koppor** [comment]
@jd-s Download https://github.com/gi-ev/LNI/blob/main/lni.cls and store it next to your `.tex` file.
