### ISSUE TITLE
Allowing inline lists (`\RequirePackage[inline]{enumitem}`)

### ISSUE THREAD

**Issue by neuschaefer** [gi-ev/LNI#170]
Currently, lni.cls imports `enumitem` without any options. This makes it impossible for users of `lni` to import `enumitem` again with different options. Therefore environments such as `enumerate*` are unavailable.

Technically, it would be simple to allow inline lists:

```diff
-\RequirePackage{enumitem}
+\RequirePackage[inline]{enumitem}
```

Is there interest in allowing inline lists?

**Comment by sieversMartin** [comment]
You should be able to do the following:
```latex
\PassOptionsToPackage{inline}{enumitem}
\documentclass[]{lni}
...
```
