### ISSUE TITLE
Unknown pattern `ngerman-x-latest`

### ISSUE THREAD

**Issue by lgalke** [gi-ev/LNI#47]
Dear LNI developers,

When using the document class, I am experiencing an error related to the `hyphsubst` package (error log below). Apparently, `ngerman-x-latest` is unknown (Running pdflatex with Texlive 2016 on Fedora 25). I tried installing / updating various packages after some googling without any success. However, the error even occurs if I pass `english` as option to the document class (I assume this is not the intended behaviour in any case).

Thanks in advance,
lgalke

```bash

latexmk -pdf  paper-lni.tex
Latexmk: This is Latexmk, John Collins, 22 April 2016, version: 4.45.
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper-lni.tex"'
------------
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./paper-lni.tex
LaTeX2e <2016/03/31>
Babel <3.9r> and hyphenation patterns for 3 language(s) loaded.
(./lni.cls
Document Class: lni 2017/04/07 v1.1BETA Official class for submissions to the `
`Lecture Notes in Informatics''
Cleared option english from global list
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hyphsubst.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty)

! Package hyphsubst Error: Unknown pattern `ngerman-x-latest'.

See the hyphsubst package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.223 \ProcessOptions*
                      \relax
```

**Comment by sieversMartin** [comment]
Are you using a vanilla TeX Live or one from the Fedora repos? If the later, I suspect a Fedora problem. Did you install a full TeX Live, is there maybe a specific hyphenation package missing?

Please check /usr/share/texlive/texmf-dist/tex/generic/config/language.dat and /usr/share/texlive/texmf-dist/tex/generic/config/language.def. Are there any entries for "ngerman" present and correct?

**Comment by lgalke** [comment]
Im using Tex Live from the fedora repos. Here are the contents of


`language.dat`:
```tex
english         hyphen.tex  % do not change!
=usenglish
=USenglish
=american
dumylang        dumyhyph.tex    %for testing a new language.
nohyphenation   zerohyph.tex    %a language with no patterns at all.
german loadhyph-de-1901.tex
ngerman loadhyph-de-1996.tex
swissgerman loadhyph-de-ch-1901.tex
```


`language.def`:

```tex
\addlanguage {USenglish}{hyphen}{}{2}{3} %%% This MUST be the first non-comment
                                         %%% line of the file

\addlanguage{german}{loadhyph-de-1901.tex}{}{2}{2}
\addlanguage{ngerman}{loadhyph-de-1996.tex}{}{2}{2}
\addlanguage{swissgerman}{loadhyph-de-ch-1901.tex}{}{2}{2}
```

I asserted that the following packages are installed:
- `texlive-hyphenat`
- `texlive-hyphenex`
- `texlive-hyph-utf8`
- `texlive-hyphen-base`
- `texlive-hyphen-german`
- `texlive-oberdiek`
- `texlive-dehyph-exptl`

**Comment by sieversMartin** [comment]
Am 17.04.2017 um 18:15 schrieb Lukas Galke:
> Im using Tex Live from the fedora repos. Here are the contents of
> 
> |language.dat|:
> 
> english         hyphen.tex  % do not change!
> =usenglish
> =USenglish
> =american
> dumylang        dumyhyph.tex    %for testing a new language.
> nohyphenation   zerohyph.tex    %a language with no patterns at all.
> german loadhyph-de-1901.tex
> ngerman loadhyph-de-1996.tex
> swissgerman loadhyph-de-ch-1901.tex
> 
> |language.def|:
> 
> \addlanguage {USenglish}{hyphen}{}{2}{3} %%% This MUST be the first non-comment
>                                          %%% line of the file
> 
> \addlanguage{german}{loadhyph-de-1901.tex}{}{2}{2}
> \addlanguage{ngerman}{loadhyph-de-1996.tex}{}{2}{2}
> \addlanguage{swissgerman}{loadhyph-de-ch-1901.tex}{}{2}{2}

Your installation seems to be buggy or at least incomplete. On a most
recent TL installation I get:
...
dumylang	dumyhyph.tex    %for testing a new language.
nohyphenation	zerohyph.tex    %a language with no patterns at all.
% from dehyph-exptl:
german-x-2017-03-31 dehypht-x-2017-03-31.tex
=german-x-latest
ngerman-x-2017-03-31 dehyphn-x-2017-03-31.tex
=ngerman-x-latest
... many more entries
% from hyphen-german:
german loadhyph-de-1901.tex
ngerman loadhyph-de-1996.tex
swissgerman loadhyph-de-ch-1901.tex


You can try to add a local language.dat to
"TEXMFLOCAL/tex/generic/config/language-local.dat" with the entries above.


-- 

Martin Sievers -- Einfach schöner publizieren

Im Alten Garten 5
54296 Trier

Telefon:  +49 (0) 651 4936567-0
Telefax:  +49 (0) 651 4936567-9
Mobil:    +49 (0) 179 7347726

Internet: http://www.schoenerpublizieren.de
E-Mail:   info@schoenerpublizieren.de

**Comment by sieversMartin** [comment]
Thinking about your other remark I agree, that the latest German hyphenation patterns do not necessarily need to be loaded when using the global option `english`. Changing this  might help all users not having installed all various language packages.

**Comment by lgalke** [comment]
Thanks to your help, I could solve the issue with my tex installation. Just for the record: adding the lines to ` `TEXMFLOCAL/...` did not help. I removed `texlive-*` packages from the fedora repos and started over with a fresh TeX Live 2016 install. From my side, the issue can be closed.

**Comment by koppor** [comment]
With MiKTeX from three days ago, we experience the same issue at [USTUTT dissertation template](https://github.com/latextemplates/uni-stuttgart-dissertation-template). Google directs me to here. No solution found, just wanted to note it down for other Googlers landing here.

**Comment by koppor** [comment]
The solution was to update MiKTeX.

**Comment by koppor** [comment]
On MiKTeX, one can solve it as follows:

1. Disable `\RequirePackage[ngerman=ngerman-x-latest]{hyphsubst}`
2. Compile the document. This way, miktex downloads additional packages. Including `hyphsubst`.
3. Enable `\RequirePackage[ngerman=ngerman-x-latest]{hyphsubst}`

I don't have a MWE yet to file it against MiKTeX. Maybe @sieversMartin knows where `hyphsubst` is contained so that MikTeX can be asked to add a dependency.

**Comment by Michael712** [comment]
Just a small addition for all looking for the same error: Make sure that the package _dehyph-exptl_ is installed. After checking/installing run `initexmf --update-fndb` and `initexmf --mklangs` .

**Comment by koppor** [comment]
State of today: not working with the hint at https://github.com/gi-ev/LNI/issues/47#issuecomment-661248739

**Comment by sieversMartin** [comment]
I'll have a look later today as I still hope to get a new version into TeX Live 2021. `hyphsubst`is no longer needed and should be replaced by `babel` macros.

**Comment by sieversMartin** [comment]
This has been fixed in v1.7

**Comment by koppor** [comment]
State of today:

```
Package babel Warning: Requested 'hyphenrules' for 'ngerman' not found:
(babel)                ngerman-x-latest.
(babel)                Using the default value. Reported on input line 75.
```

Installing the package [oberdiek](https://ctan.org/pkg/oberdiek) helped.

**Comment by koppor** [comment]
Follow-up issue on MikTeX repository: https://github.com/MiKTeX/miktex-packaging/issues/238
