### ISSUE TITLE
Unknown option `straightquotes' for package `newtxtt'

### ISSUE THREAD

**Issue by white-gecko** [gi-ev/LNI#49]
Compiling the `lni-author-template.tex` with `xelatex` and `pdflatex` results in the following error.

```
! LaTeX Error: Unknown option `straightquotes' for package `newtxtt'.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.40 \DeclareRobustCommand
                          \ttzfamily
```

My versions are:

```
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2015/dev/Debian) (preloaded format=latex)
 restricted \write18 enabled.

This is XeTeX, Version 3.14159265-2.6-0.99992 (TeX Live 2015/dev/Debian) (preloaded format=xelatex)
 restricted \write18 enabled.
```

**Comment by sieversMartin** [comment]
This is probably not an issue of the TeX engine, but the package version for the `newtxtt` font.

I'll check that and maybe add a "compatibility" option. However, I rather suggest upgrading your installation, at least when TeX Live 2017 is released.

**Comment by sieversMartin** [comment]
The Option `straightquotes` was added for version v1.05 released 2014/11/18.
