### ISSUE TITLE
xelatex support

### ISSUE THREAD

**Issue by white-gecko** [gi-ev/LNI#52]
Currently the lni class can't be used with xelatex. With #51 I would like to start getting support for XeLaTeX as well.

**Comment by sieversMartin** [comment]
A problem I see is the font support. The `lni` class uses the `newtxtext` package which is for pdfTeX only. I have to check whether we can use the fonts with `XeTeX` and maybe `LuaTeX` as well easily.

**Comment by sieversMartin** [comment]
I added partial support (d211750)
