### ISSUE TITLE
biblatex option: bbx file cant be found

### ISSUE THREAD

**Issue by white-gecko** [gi-ev/LNI#55]
When I add the `biblatex` option to the document class I get the following error message:

```
! Package biblatex Error: Style 'LNI' not found.

See the biblatex package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.10838 \RequireBibliographyStyle{\blx@bbxfile}
                                               
``` 

There are only the `lni.bst` and `lnig.bst` files in the repository. Where can I find the correct bibliography style for biblatex?

**Comment by sieversMartin** [comment]
You have to install the package `biblatex-lni`. If it is not available via your TeX distribution you can get it from [CTAN](https://www.ctan.org/pkg/biblatex-lni?lang=de).
Copying the files `.bbx`, `.cbx` and `.lbx` into your document's directory is sufficient. However, an installation into your local TEXMF tree is preferable.

**Comment by white-gecko** [comment]
Maybe there could also be a reference in the README for this. (In my case I move all the relevant file to paper-repo so all dependencies are shipped to all collaborators, making them install all the stuff would rise the barrier for collaboration ;-) )

I think this is related to the same issue, because now since I've copied over these three files I get the following errors:

```
! Package xkeyval Error: `giveninits' undefined in families `blx@opt@pre'.

See the xkeyval package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.48 }
      
? 
! Undefined control sequence.
l.61 \DeclareDelimFormat
                        [bib]{nametitledelim}{\nametitledelim}
? 
```

**Comment by white-gecko** [comment]
Seams to be a problem with my biblatex version: https://tex.stackexchange.com/questions/316377/biblatex-no-author-year-delimiter-for-one-literature-type#316380

**Comment by sieversMartin** [comment]
Please read the requirements for `biblatex-lni`: 
This is a bibla­tex style for LNI, the Lec­ture Notes in In­for­mat­ics of the Ge­sellschaft für In­for­matik e.V.. It re­quires at least bibla­tex 3.5 and biber 2.6.

**Comment by sieversMartin** [comment]
There was a critical change in the way names are handled. Therefore older versions of `biblatex` will have to be supported separately.

**Comment by saleemrazam** [comment]
Hi, 
I am getting the following error:
! Package biblatex Error: Style 'LNI' not found.

I have copy pasted the cbx, lbx etc files in the texmf tree, still the error persists. can you help?

Thank you

**Comment by sieversMartin** [comment]
It should not be necessary to manually install the biblatex files. If you have a not too old MiKTeX or TeX Live please install biblatex-lni with the package manager.

If you still want to install it manually don't forget to update your database with `texhash`

**Comment by saleemrazam** [comment]
I installed texlive 2020, and biber was 2.14 which I could not be updated to 2.6 which I downloaded from sourceforge, again installed texlive-full and this again 2015 version, and tlmgr seems does not work with 2015. I try to indstall tlmgr biblatex-lni and I get this error "tlmgr install: package biblatex-lni not present in repository. tlmgr: action install returned a warning."

**Comment by sieversMartin** [comment]
Installing TeX Live 2020 is fine. Please do not mix old stuff. Biober 2.6 is *older* than 2.14 and should not be used! Stick to your installation. If you installed a full version, everything is there.
If your problems persist, please add an minimal working example and your log file.

**Comment by saleemrazam** [comment]
Ok, thanks. The command line compilation works fine, it can generate my pdf with citation entries correctly. I use the following commands at the command line `pdflatex main` and then `biber.main` and then again `pdflatex main`. However, when I run it through texmaker it gives me following error as attached. 
![image](https://user-images.githubusercontent.com/11177427/82896293-03530e00-9f56-11ea-9af5-006079ed27c8.png)

**Comment by sieversMartin** [comment]
Are you compiling the exact same file on the command line and in TeXmaker? When does the error occur? Right at the first run? Is TeXmaker configured to run biber?
Could you please try to run a minimal example and post the file here as well?

**Comment by saleemrazam** [comment]
Yes, I have changed Texmaker setting accordingly. I actually took your MWE example that I downloaded from the CTAN. That again from command line works fine, but with Texmaker it generates errors. see the attached image which contains the error and MWE. 
![MWE](https://user-images.githubusercontent.com/11177427/82899951-110b9200-9f5c-11ea-9cb4-78ebc1e4f786.png)

**Comment by sieversMartin** [comment]
There is something very wrong going on with your installations ... Your log file says TeX Live 2015 and uses some pdflatex format from 2020

Please remove the old TeX Live 2015 completely and only use the up-to-date 2020 version. You can also try to set another path (or just "pdflatex") in TeXmaker to really use the TL 2020 binaries. I guess that is the difference between command line and gui.
