### ISSUE TITLE
Support of subcaption package

### ISSUE THREAD

**Issue by stachch** [gi-ev/LNI#59]
I am using the subcaption package. In the default configuration the font size for the main figure captions changes from 9pt to 10pt.
This could be solved by adding the following two lines

    \RequirePackage{subcaption}
    \captionsetup{skip=7pt,font=small,list=true,hypcap=true}

to the style file.

**Comment by sieversMartin** [comment]
Well, yes, this solves the problem as far as I can see.

However, your issue points to a more general problem: The `lni` class  redefines the macro `\@makecaption` directly. When you now load `subcaption` you load `caption` implicitly. The later, however, changes the complete caption mechanism, i.e. it throws away the class's modifications. It uses its own macro `\caption@@make` to control the caption's layout.

One way out of this dilemma would be to directly use the `caption` package within the `lni` class. The alternative would be to check for modifications at the end of the preamble and to turn them back. This could even be done very elegantly using the `scrlfile` package from the KOMA-Script bundle.

@koppor What do you think?

**Comment by koppor** [comment]
+1 for using the  [caption](https://www.ctan.org/pkg/caption) package. It is maintained and we should not implement custom solutions.

**Comment by sieversMartin** [comment]
I just checked. The definition only adds `\small` to `\@makecaption`. Thus I will add the `caption` package.

**Comment by sieversMartin** [comment]
I changed the handling of captions.

**Comment by sieversMartin** [comment]
I do however **not** load the `subcaption` package automatically.
