### ISSUE TITLE
Add hint to word limit in abstract

### ISSUE THREAD

**Issue by stachch** [gi-ev/LNI#60]
The Word template states:

> Abstract: This is a brief overview of the paper, which should be 70 to 150 words long and include the most relevant points

Further, @heseba required a single paragraph in the abstract which seems to be a general guideline.

**Comment by sieversMartin** [comment]
So, you want me to add a small text to the template?

**Comment by koppor** [comment]
Yes, I think https://github.com/gi-ev/LNI/blob/master/lni-author-template.tex#L32 would be the place to be. Just pasting a modified version of the text:

> This is a brief overview of the paper, which should be 70 to 150 words long and include the most relevant points. This has to be a single paragraph.

**Comment by sieversMartin** [comment]
Done.
