### ISSUE TITLE
Larger title and smaller headings

### ISSUE THREAD

**Issue by koppor** [gi-ev/LNI#61]
I checked 6317278 whether it affects other font sizes.

And IMHO, yes, it does:

- [x] The title font is a bit <s>larger</s> smaller
- [ ] the spacing of the heading got smaller: there is (i) less space between the two lines and (ii) less space between the text and the headsepline.
- [x] Size of Listing caption
- [x] Spacing of table rows
- [x]  Spacing before a caption.

Equation spacing is OK.

I really like using existing code, but seeing that it causes troubles, maybe we should use the "hack" of @sieversMartin (https://github.com/gi-ev/LNI/issues/59#issuecomment-317984429) to use `scrlfile`?

## Before 6317278:

![grafik](https://user-images.githubusercontent.com/1366654/28687466-c4971c22-730e-11e7-88b4-8b53b5f1b83f.png)

## After

![grafik](https://user-images.githubusercontent.com/1366654/28687531-05dd06a6-730f-11e7-8a74-0b4f8c0c1739.png)

## Before

![grafik](https://user-images.githubusercontent.com/1366654/28687692-8aec0130-730f-11e7-968d-4f2f451967a7.png)

## After

![grafik](https://user-images.githubusercontent.com/1366654/28687744-b275913a-730f-11e7-91c9-0e9a7f9a88df.png)

**Comment by sieversMartin** [comment]
Thank you for the comparison. Let me explain, what I did (or at least what I think I did)

I redefined `\small` to `\fontsize{9}{10}` and `\large` to `{14}{17}`. I then replaced all explicit calls of `\fontsize` by a concrete size macro.

I am aware that some `\small` calls had been used before and therefore these calls now result in 1pt less baselineskip. However, this does not explain all changes in my opinion.

The same is valid for the caption skip, where I replaced explicit settings by the `caption`'s setup.

I guess I have to check once more, whether we can get this right.

**Comment by sieversMartin** [comment]
Well, I found a reason at least for the title font. I used `\@xivpt` which is actually not 14pt, but 14.4pt.

**Comment by sieversMartin** [comment]
Would you like to check again using the most recent developer version?

**Comment by koppor** [comment]
Two issues fixed, three remain:

![grafik](https://user-images.githubusercontent.com/1366654/32565185-9ee83a3e-c4b6-11e7-8d62-c3f1a38785ae.png)

![grafik](https://user-images.githubusercontent.com/1366654/32565313-fbd6c0d0-c4b6-11e7-8e08-e387a32d6485.png)

**Comment by koppor** [comment]
Is it because of some of the following changes?

https://github.com/gi-ev/LNI/commit/63172782e6b33a9f90c46a656983b90c0fa3894b#diff-1fbc20f5d285bbdef700c0c39ab085c6R219

**Comment by sieversMartin** [comment]
Yes, I found at least one remaining bug regarding the running heading.

**Comment by sieversMartin** [comment]
Found another one regaring the caption. Same thing. Was `\small` before and now, but `\small` was changed from {9}{11} to {9}{10}, i.e. a smaller line spacing.

Sorry.

**Comment by sieversMartin** [comment]
Maybe you want to test again. I am sure about the table line, the rest should be fixed.

**Comment by koppor** [comment]
Title font size still change - the smaller one is the new one. Looks uglier, I would say?!

![sizechange gif](https://user-images.githubusercontent.com/1366654/32636195-09cb63fa-c5b4-11e7-82b8-afac2ff239f3.gif)

The spacings are moved somehow. I lean towards saying that the old spacing looks better, because of slight more distance between the table lines.

![sizechange gif](https://user-images.githubusercontent.com/1366654/32636421-001165fc-c5b5-11e7-9817-13cb934aa238.gif)

**Comment by sieversMartin** [comment]
I am a bit puzzled. Originally the title was set using `\fontsize{14}{17}\selectfont`. I changed that to `\Large` which was wrong, because that gives `\fontsize{14.4}{17}\selectfont` by default.
Therefore I added `\renewcommand\Large{\@setfontsize\Large{14}{17}}` to the class file.

So comparing version `dc22fb4a6f9d8ec1feb5150ca04e0c220091cbc6` with the current development version should give the same result.

Is it the same font?

After all I wanted to make it more elegant, but apparently made it worse ...

**Comment by koppor** [comment]
Heading: Yeah, you are right. Here the video from v1.3 to 6317278 to current master (22e9273eff):

![linespread gif](https://user-images.githubusercontent.com/1366654/32843514-4b87eaaa-ca20-11e7-870a-bfb68a2678ca.gif)

The issue is that the line spacing in the heading changed from v1.3 to 6317278 . So, let's keep the title as is, but fix the spacing in the heading? Alternatively, I try to include the spacing adjustments in the [proceedings template](https://gi-ev.github.io/LNI-proceedings/).

The table spacing still changes:

![linespread2 gif](https://user-images.githubusercontent.com/1366654/32843676-a0b49d48-ca20-11e7-9d57-dde1d6c5ec95.gif)

OK, the spacing is better because of more space for authors :)

**Comment by sieversMartin** [comment]
Thank you for the comparisons. I don't understand why `\oldsmall` which is the original `\small` in the current master and `\small` (the original) in v1.3 do end up in different results.

It would be easiest to go back to the explicit font size settings if that problems persists. I will do that within the next days.

**Comment by koppor** [comment]
I think, we can keep the current settings. Less spacing in tables leaves the authors more space in the paper.

Regarding the heading space, I would also opt for leaving it as is, because the difference are very minimal. We can work on it if some proceedings authors start to wonder about it.

**Comment by sieversMartin** [comment]
Well, it is only some very small modification to get back to the old settings (and the old design).

Should we do that? As you said, it is only a very small difference, so we should go for the old solution.

**Comment by sieversMartin** [comment]
Sorry, I saw your mail regarding this matter too late ... I leave it up to you. So if you think we should go with the new settings, then we'll do.

**Comment by koppor** [comment]
In the .docx, it is also a small spacing:

![grafik](https://user-images.githubusercontent.com/1366654/34943064-4b7eeb44-f9fa-11e7-853c-97cb74865364.png)

So, I think, we should keep the current solution.
