### ISSUE TITLE
Add package upquote

### ISSUE THREAD

**Issue by koppor** [gi-ev/LNI#69]
I think, [upquote](https://www.ctan.org/pkg/upquote) is a useful package for listings. Should we just add `\usepacakge{upquote}` as default?

See https://tex.stackexchange.com/a/341057/9075 for more information.

**Comment by sieversMartin** [comment]
Well, I personally have been using it for years now. So, why not?
We could just use the `upquote` option of the `listings` package. However both solutions rely on `textcomp`, so we probably have to add a switch for `pdflatex` here.
