### ISSUE TITLE
Option for disabling running header necessary?

### ISSUE THREAD

**Issue by sieversMartin** [gi-ev/LNI#77]
I got an email today asking how to remove the running header as this was requested by a conference call for papers ("Wissensmanagement Konferenz").

The solution is not complicated:
```latex
\pagestyle{empty}
\fancypagestyle{plain}{%
   \fancyhead{}
   \renewcommand{\headrulewidth}{0.0pt}
}%
```

Howver, I wonder, whether this is a common usecase so that an option for the document class would be a good idea.

@koppor What do you think?

**Comment by koppor** [comment]
+1 for a classoption. LNCS uses "norunningheads".

Reasoning: Most editors seem to use other tooling than the provided at
https://gi-ev.github.io/LNI-proceedings/. To ease the other tooling,
headers and footers should not be present in the camera ready version.

Am Mi., 20. Feb. 2019, 09:51 hat Martin Sievers <notifications@github.com>
geschrieben:
