### ISSUE TITLE
LNI collides with package datetime

### ISSUE THREAD

**Issue by fengelhardt** [gi-ev/LNI#82]
When using `\usepackage{datetime}`, in a lni-class document, a redefinition of `\@year` occurs.

Minimal example:

```
\documentclass[utf8,biblatex,english]{lni}

\usepackage{datetime}

\begin{document}

\title[Ein Kurztitel]{Ein sehr langer Titel über mehrere Zeilen mit sehr vielen Worten und noch mehr Buchstaben}

\author[Vorname1 Nachname1 \and Vorname2 Nachname2]
{Vorname1 Nachname1\footnote{Universität, Abteilung, Straße, Postleitzahl Ort, Land \email{emailaddress@author1}} \and
 Vorname2 Nachname2\footnote{University, Department, Address, Country \email{emailaddress@author2}}}
\startpage{11} % Beginn der Seitenzählung für diesen Beitrag
\editor{Herausgeber et al.}    % Namen der Herausgeber
\booktitle{Name-der-Konferenz} % Name des Tagungsband; optional Kurztitel
\year{2017}
\maketitle


\end{document}
```

Compiling it with pdflatex, it results in an error message:

`
! LaTeX Error: Command \@year already defined.
               Or name \end... illegal, see p.192 of the manual.
`

The error is circumvented by removing the `\usepackage{datetime}` above.

**Comment by sieversMartin** [comment]
What do you need the package datetime for?

⁣Gesendet mit TypeApp ​

**Comment by sieversMartin** [comment]
Am 24.02.20 um 15:30 schrieb Martin Sievers:
> What do you need the package datetime for?

datetime is obsolete and succeeded by datetime2. Have you tried with
this package? AFAIK there is no \@year defined there.

**Comment by fengelhardt** [comment]
Thank you @sieversMartin ! I have to include a custom .sty file that used datetime. I could replace it by datetime2 with small refactoring, and it works now. 

So I think the issue can be closed, as datetime is indeed deprecated.
