### ISSUE TITLE
[Suggestion] Change `\year` macro

### ISSUE THREAD

**Issue by sieversMartin** [gi-ev/LNI#85]
Following a discussion at https://tex.stackexchange.com/questions/573374/glossaries-package-incompatible-with-documentclasslni I would like to change the `\year` macro to `\submissionyear` or the standard `\date` macro. Redefining a macro like `\year`, which should be as "stable" as possible, was not the best decision although it has been working so long.

Any preferences from @koppor or @sstrecker?

**Comment by sstrecker** [comment]
\submissionyear sounds fine for a temporary value (until a submission is accepted).

\yearofpublication (or similar) sounds better after a submission is accepted and published.

**Comment by koppor** [comment]
Da man sowieso die Herausgeber angeben muss, bin ich auch für `\yearofpublication`.

Gegen `\date` spricht, dass man am Ende nur das Jahr braucht und die User sowieso eher selten `\date` benutzen.

**Comment by sieversMartin** [comment]
Done for v1.7.0
