### ISSUE TITLE
Stray comma in @misc bibliography entries

### ISSUE THREAD

**Issue by GCE-Galotta** [gi-ev/LNI#97]
Citing a `@misc` reference causes a stray comma before the title in the bibliography. E.g. this reference

```
@misc{https://doi.org/10.48550/arxiv.1912.07756,
  doi = {10.48550/ARXIV.1912.07756},
  note = {\url{https://arxiv.org/abs/1912.07756} [2022-04-01]},
  url = {https://arxiv.org/abs/1912.07756},
  author = {Nanni, Loris and Maguolo, Gianluca and Paci, Michelangelo},
  title = {Data augmentation approaches for improving animal audio classification},
  keywords = {Machine Learning (cs.LG), Sound (cs.SD), Audio and Speech Processing (eess.AS), Machine Learning (stat.ML), FOS: Computer and information sciences, FOS: Computer and information sciences, FOS: Electrical engineering, electronic engineering, information engineering, FOS: Electrical engineering, electronic engineering, information engineering},
  publisher = {arXiv},
  year = {2019},
  copyright = {arXiv.org perpetual, non-exclusive license}
}
```

generates this result with a comma before "Data augmentation..."

[NMP19] Nanni, Loris; Maguolo, Gianluca; Paci, Michelangelo: **,** Data augmentation approaches for improving animal audio classification, 2019. https://arxiv.org/abs/1912.07756 [2022-04-01].

**Comment by GCE-Galotta** [comment]
https://www.overleaf.com/9487574534nvndbtwgsvng

**Comment by sieversMartin** [comment]
Okay, a BibTeX problem then. I'll check. In general it may be a good idea to switch to `biblatex-lni` which is supported with the `biblatex` option. Check the documentation for more details.

**Comment by GCE-Galotta** [comment]
Yes, this is only in bibtex, not biblatex. If it is recommended to use biblatex, shouldn't it be the default setting? Sorry, I'm not that deep into the subject of bib(la)tex.

**Comment by sieversMartin** [comment]
Well, that class has some history :-) Therefore we haven't switched to biblatex as the default yet.

Regarding your issue, I think I found a solution.
